name: Compiler

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Cache maven packages
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-packages
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: latest

      - name: Run tests
        run: clojure -M:test

      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: target/coverage/
